annotations:
  artifacthub.io/changes: |-
    - "update web hook cert gen to latest release v20231226-1a7112e06"
    - "Update Ingress-Nginx version controller-v1.9.6"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: latest
dependencies:
- condition: appsec.tuning.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.2.8
keywords:
- ingress
- nginx
kubeVersion: '>=1.20.0-0'
name: open-appsec-k8s-nginx-ingress
sources:
- https://github.com/kubernetes/ingress-nginx
version: 4.9.1
