annotations:
  artifacthub.io/changes: |
    - "Added a doc line to the missing helm value service.internal.loadBalancerIP (#9406)"
    - "feat(helm): Add loadBalancerClass (#9562)"
    - "added helmshowvalues example (#10019)"
    - "Update Ingress-Nginx version controller-v1.8.1"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.8.1
keywords:
- ingress
- nginx
kubeVersion: '>=1.20.0-0'
name: open-appsec-k8s-nginx-ingress
sources:
- https://github.com/kubernetes/ingress-nginx
version: 4.7.1
