annotations:
  artifacthub.io/changes: '- "Update Ingress-Nginx version controller-v1.10.0"'
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: latest
dependencies:
- condition: appsec.tuning.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.2.8
keywords:
- ingress
- nginx
kubeVersion: '>=1.20.0-0'
name: open-appsec-k8s-nginx-ingress
sources:
- https://github.com/kubernetes/ingress-nginx
version: 4.10.0
