annotations:
  artifacthub.io/changes: |
    - "[helm] Support custom port configuration for internal service (#9846)"
    - "Adding resource type to default HPA configuration to resolve issues with Terraform helm chart usage (#9803)"
    - "Update Ingress-Nginx version controller-v1.7.1"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.7.1
keywords:
- ingress
- nginx
kubeVersion: '>=1.20.0-0'
name: open-appsec-k8s-nginx-ingress
sources:
- https://github.com/kubernetes/ingress-nginx
version: 4.6.1
