name: 'build'
on: push

jobs:
  build-on-aws-instace:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: 'check out repository'
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
       registry: ghcr.io
       username: ${{ github.actor }}                           
       password: ${{ secrets.GITHUB_TOKEN }}
       
    - name: Build the agent
      run: |
         ./scripts/entry.sh agent ubuntu focal
    
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./output/agent/openappsec-focal.tar.gz
    
